### ISSUE TITLE
Basket breaks on refresh

### ISSUE THREAD

**Issue by LarveyOfficial** [Michigan-Tech-Courses/frontend#44] opened 2023-10-31 01:31 UTC
I noticed that when refreshing the basket breaks and shows that you have no basket,
pressing create new basket does nothing (although it actually does create new baskets)

Only way to get the basket back is to go to another page (about or transfer courses) and then back to the courses tab.

https://github.com/Michigan-Tech-Courses/frontend/assets/39219859/4d36ce50-4796-4b2e-b74f-c6d25afb28e5

**Comment by codetheweb** [comment] 2023-11-01 03:11
Strange, was able to reproduce.

**Comment by codetheweb** [comment] 2023-11-01 05:06
I think this was caused by a dependency update but having a hard time tracking it down. Will hopefully resolve tomorrow.

**Comment by codetheweb** [comment] 2023-11-02 03:57
Fixed in 1985572e78a00b6632b62642c2b1d61c439d9418.

Thanks for all the bug reports. :)

**Closed by codetheweb** 2023-11-02 03:57 UTC
